### ISSUE TITLE
Comments for passenger/Services.Pax.Locale-RfC.md

### ISSUE THREAD

**Issue by martinosk** [dfds/component-rfc#5]
#4 
Suggestions:

Perhaps the Services.Pax prefix in the name is not needed. Could it be DFDS.Locale instead?

> ## 8 Inner architecture
Perhaps this service is a candidate for a lambda function or maybe even just some files served directly from S3. Would that be too weird?

**Comment by pywellj** [comment]
> Perhaps the Services.Pax prefix in the name is not needed. Could it be DFDS.Locale instead?

Yeah agreed. This seems like something that could be used anywhere.

**Comment by martinosk** [comment]
@thsendfds Should this RFC be rejected? It looks like the service won't be created.

**Comment by thsendfds** [comment]
Hm... I'm not a fan of S3, but the Lambda stuff could work. Though I think it would be easier to grasp/maintain for the majority of the developers if it were a regular plain "old" microservice :-) But the vote is still out whether to do this or not... November 1st will be deadline for a decision.

**Comment by thsendfds** [comment]
We'll bring it up again when the need re-appears.
